# Generated by Django 5.0.6 on 2024-05-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='memberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('contact_number', models.TextField(max_length=15)),
                ('gender', models.TextField(max_length=10)),
                ('member_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Member_Profile', to=settings.AUTH_USER_MODEL)),
                ('playing_in', models.ManyToManyField(to='api.category')),
            ],
        ),
    ]
