# Generated by Django 5.0.6 on 2024-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_memberprofile_comments_memberprofile_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='monthly_fee_pending',
            new_name='fee_pending',
        ),
    ]
