# Generated by Django 5.0.6 on 2024-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_monthly_fee_pending_memberprofile_fee_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
