# Generated by Django 5.0.6 on 2024-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_memberprofile_is_admin_memberprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='achievements',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
