# Generated by Django 5.0.6 on 2024-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memberprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='school_college',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
